# rabbitmq.conf — автосборка кластера из 3 нод через classic_config peer discovery.
# Монтируется в каждую ноду read-only. Erlang cookie задаётся в compose (одинаковый для всех).
loopback_users.guest = false
listeners.tcp.default = 5672

cluster_formation.peer_discovery_backend = classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbit1
cluster_formation.classic_config.nodes.2 = rabbit@rabbit2
cluster_formation.classic_config.nodes.3 = rabbit@rabbit3

cluster_partition_handling = pause_minority
vm_memory_high_watermark.relative = 0.6
# для Сценария 3 (JSON ~20MB) поднимаем допустимый размер кадра:
frame_max = 33554432
